version: 2
updates:
  - package-ecosystem: gradle
    directory: "/finance-backend"
    schedule:
      interval: weekly
      time: "04:00"
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: "/finance-frontend"
    schedule:
      interval: weekly
      time: "04:00"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-patch" ]