services:
  backend:
    image: zrdzn/finance-backend:latest
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    env_file:
      - .env
    expose:
      - "8080"
  frontend:
    image: zrdzn/finance-frontend:latest
    ports:
      - "3000:3000"
    expose:
      - "3000"
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
  database:
    image: postgres
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    expose:
      - '5432'
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
  storage:
    image: minio/minio
    restart: always
    volumes:
      - storage:/data
    environment:
      - MINIO_ROOT_USER=${STORAGE_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${STORAGE_SECRET_KEY}
      - MINIO_SITE_REGION=${STORAGE_REGION}
      - MINIO_SERVER_URL=${STORAGE_ENDPOINT}
    ports:
      - '9000:9000'
      - '9001:9001'
      - '9002:9002'
    entrypoint: ['minio', 'server', '/data', '--console-address', ':9002']

volumes:
  database:
    driver: local
  storage:
    driver: local