services:
  backend:
    image: zrdzn/finance-backend:latest
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    env_file:
      - .env
    expose:
      - "8080"
  frontend:
    image: zrdzn/finance-frontend:latest
    ports:
      - "3000:3000"
    expose:
      - "3000"

volumes:
  database:
    driver: local