server:
  port: ${SERVER_PORT}
  tomcat:
    max-swallow-size: 10MB
    max-http-form-post-size: 10MB
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    banner-mode: off
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_CLIENT_ID_GOOGLE}
            client-secret: ${OAUTH_CLIENT_SECRET_GOOGLE}
            redirect-uri: ${OAUTH_CLIENT_REDIRECT_URI_GOOGLE}
          scope:
            - email
            - profile
  liquibase:
    change-log: database/changelog-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          auth: ${MAIL_AUTH}
          starttls:
            enable: ${MAIL_STARTTLS}
    from: ${MAIL_FROM}
client:
  url: ${CLIENT_URL}
api:
  url: ${NEXT_PUBLIC_API_URL}
storage:
  access-key: ${STORAGE_ACCESS_KEY}
  secret-key: ${STORAGE_SECRET_KEY}
  region: ${STORAGE_REGION}
  endpoint: ${STORAGE_ENDPOINT}
  predefined-buckets:
    - "avatars"
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
totp:
  secret:
    length: 16
  code:
    length: 6
ai:
  api-key: ${OPENAI_API_KEY}
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.csrf: TRACE
