server:
  port: ${SERVER_PORT}
spring:
  main:
    banner-mode: off
  liquibase:
    change-log: database/changelog-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
client:
  url: ${CLIENT_URL}