server:
  port: ${SERVER_PORT}
spring:
  main:
    banner-mode: off
  liquibase:
    change-log: database/changelog-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          auth: false
          starttls:
            enable: false
    from: ${MAIL_FROM}
client:
  url: ${CLIENT_URL}
springdoc:
  swagger-ui:
    path: "/swagger.html"
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
totp:
  secret:
    length: 16
  code:
    length: 6
