spring:
  main:
    banner-mode: off
  liquibase:
    change-log: database/changelog-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 20
  jpa:
    hibernate:
      ddl-auto: validate