package dev.zrdzn.finance.backend.audit

enum class AuditAction {

    TRANSACTION_CREATED,
    TRANSACTION_UPDATED,
    TRANSACTION_DELETED,
    TRANSACTION_IMPORTED,
    TRANSACTION_EXPORTED,

    TRANSACTION_PRODUCT_CREATED,

    SCHEDULE_CREATED,
    SCHEDULE_DELETED,

    CATEGORY_CREATED,
    CATEGORY_DELETED,

    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,

}
