--liquibase formatted sql
--changeset finance:0
CREATE TYPE "audit_action" AS ENUM (
    'TRANSACTION_CREATED',
    'TRANSACTION_UPDATED',
    'TRANSACTION_DELETED',
    'TRANSACTION_EXPORTED',
    'TRANSACTION_PRODUCT_CREATED',
    'CATEGORY_CREATED',
    'CATEGORY_DELETED',
    'PRODUCT_CREATED',
    'PRODUCT_UPDATED',
    'PRODUCT_DELETED'
);