package dev.zrdzn.finance.backend

enum class EnvironmentProperty {

    SERVER_PORT,
    CLIENT_URL,
    DATABASE_URL,
    DATABASE_USERNAME,
    DATABASE_PASSWORD,
    MAIL_HOST,
    MAIL_PORT,
    MAIL_USERNAME,
    MAIL_PASSWORD,
    MAIL_FROM,
    STORAGE_ACCESS_KEY,
    STORAGE_SECRET_KEY,
    STORAGE_REGION,
    STORAGE_ENDPOINT

}